hydra:
  output_subdir: null
  run:
    dir: /network/scratch/j/juan.duque/hydra/

seed: 1
agent_type: "vip_v2"
reward_window: 10
num_episodes: 1000000
env: "cg"
base_agent:
  gamma: 0.99
  hidden_size: 128
  num_layers: 0
  opt_type: "eg"
vip_agent:
  steps_reset: 20
  num_rollouts: 20
  rollout_len: 20
  communication_len: 10
  representation_size: 16
  history_len: 2
  collab_weight: 1
  exploit_weight: 1
  entropy_weight: 1
vip_agent_v2:
  batch_size: 32
  steps_reset: 20
  num_rollouts: 20
  rollout_len: 20
  communication_len: 10
  representation_size: 16
  history_len: 2
  collab_weight: 1
  exploit_weight: 1
  entropy_weight: 1
  epsilon: 0.2
vip_actor_v2:
  communication_len: 10
  representation_size: 16
  history_len: 2
optim:
  lr: 0.00001
  momentum: 0.9
  weight_decay: 1e-5
  beta_1: 0.9
  beta_2: 0.999